# Generated by Django 3.1.4 on 2021-07-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
